version: '3.8'
services:
  backend: 
    build: .
    environment:
    ports:
    - '5000:5000'
    networks:
      - networkName
    depend_on:
    volumes:
    - 
    command: 


  client: 
    build: .
    environment:
    ports:
    - '3000:3000'
    networks:
    - networkName
    depend_on:
    volumes:
    - version
    links:
    - backend
    
volumes:

networks:
